version: '3'

services:
  mongodb:
    image: mongo:latest
    container_name: mongo-co
    ports:
      - '27017:27017'
    volumes:
      - mongodb_data:/data/db
    networks:
      - app-network

  air-quality-api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: air-quality-api-co
    ports:
      - '4000:4000'
    depends_on:
      - mongodb
    env_file:
      - .env
    networks:
      - app-network

# Define custom bridge network
networks:
  app-network:
    driver: bridge

# Define MongoDB data volume
volumes:
  mongodb_data:
